### ISSUE TITLE
No visualization if there is a single data point

### ISSUE THREAD

**Issue by scholtzan** [mozilla/looker-ci-line-chart#42]
If there is only a single data point then the visualization is basically transparent. This is probably due to the individual points not having any color/style assigned to them. We'll need to fix this to be useful for the MR dashboards

cc @mikewilli

**Comment by mikewilli** [comment]
Pretty sure this would just be a change to the point radius, which we have set to 0 to mimic the look of the built-in charts. Point radius > 0 would draw a circle at each datapoint, which we currently only do on hover.

One solution would be to just check if the dataset length is 1, and if so then set a radius greater than 0 (e.g., `data.length > 1 ? 0 : 4`).

Here's where the point radius is set for each of the upper/point/lower datasets:
Upper: https://github.com/mozilla/looker-ci-line-chart/blob/main/src/ci-line-chart.js#L383
Point: https://github.com/mozilla/looker-ci-line-chart/blob/main/src/ci-line-chart.js#L403
Lower: https://github.com/mozilla/looker-ci-line-chart/blob/main/src/ci-line-chart.js#L423
